apiVersion: v1
kind: Service
metadata:
  name: portfolio-api
  labels:
    app.kubernetes.io/name: portfolio-api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: portfolio
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: portfolio-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
      appProtocol: http
