apiVersion: v1
kind: Service
metadata:
  name: portfolio-web
  labels:
    app.kubernetes.io/name: portfolio-web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: portfolio
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: portfolio-web
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
      appProtocol: http
