apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio-production

resources:
  - ../../base
  - namespace.yaml
  - api-hpa.yaml
  - web-hpa.yaml
  - api-pdb.yaml
  - web-pdb.yaml

patches:
  - path: api-environment-patch.yaml

replicas:
  - name: portfolio-api
    count: 2
  - name: portfolio-web
    count: 2

labels:
  - pairs:
      app.kubernetes.io/instance: portfolio-production
      environment: production
    includeSelectors: false
    includeTemplates: true
