apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio-production

resources:
  - ../../base
  - ../../platform/alicloud-alb/ingress
  - namespace.yaml
  - api-hpa.yaml
  - web-hpa.yaml
  - api-pdb.yaml
  - web-pdb.yaml

patches:
  - path: api-environment-patch.yaml
  - path: ingress-path-patch.yaml

labels:
  - pairs:
      app.kubernetes.io/instance: portfolio-production
      environment: production
    includeSelectors: false
    includeTemplates: true
