apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace-dev.yaml
  - namespace-test.yaml
  - namespace-perf.yaml
  - namespace-staging.yaml
  - namespace-production.yaml
  - service-deployer-cluster-role.yaml
